<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tgfit"
 *
 * Auto generated by Extension Builder 2016-10-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TG-Fit Template',
	'description' => '',
	'category' => 'templates',
	'author' => 'Joe Schäfer',
	'author_email' => 'mail@schaefer-webentwicklung.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.4.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '8.5.1-8.99.99',
			'gridelements' => '8.0.0-dev',
			'bootstrap_grids' => '',
			'mask' => '',
			'realurl' => '',
			'dd_googlesitemap' => '',
			't3monitoring_client' => '',
			'cs_seo' => '',
			'sourceopt' => '',
			'scriptmerger' => '',
			// Sysextensions
			'opendocs' => '',
			'recycler' => '',
			'rte_ckeditor' => '',
		),
		'conflicts' => array(
			'rtehtmlarea' => ''
		),
		'suggests' => array(
			'rx_unrollsavebuttons' => '',
			'go_maps_ext' => '',
			'frontend_editing' => '',
		),
	),
);
