<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tgfit"
 *
 * Auto generated by Extension Builder 2016-10-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TG-Fit Template',
	'description' => '',
	'category' => 'templates',
	'author' => 'Joe Schäfer',
	'author_email' => 'mail@schaefer-webentwicklung.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
